#! /bin/bash
if [ $# -ge 3 ]; then
	inputSize=$1
	inputFile=$2
	verLevel=$3
elif [ $# -eq 2 ]; then
	inputSize=$1
	inputFile=$2
	verLevel=0
elif [ $# -eq 1 ]; then
	inputSize=$1
	inputFile="jacobi.c_ver1"
	verLevel=0
else
	inputSize=256
	inputFile="jacobi.c_ver1"
	verLevel=0
fi

openarcrt="../../../../openarcrt"
openarclib="../../../../lib"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ -f "$inputFile" ]; then
    cp "$inputFile" "jacobi.c"
else
    cp "jacobi.c_ver1" "jacobi.c"
fi

if [ "$inputSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__inputSize__|${inputSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt jacobi.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; jacobi_ACC"
echo "or"
echo "\$ cd bin; jacobi_ACC -i ITER"
echo ""
