#! /bin/bash
if [ $# -ge 2 ]; then
	inputFile=$1
	verLevel=$2
elif [ $# -eq 1 ]; then
	inputFile=$1
	verLevel=0
else
	inputFile="vecadd.c_v3"
	verLevel=0
fi

if [ "${OPENARC_INSTALL_ROOT}" = "" ]; then
    OPENARC_INSTALL_ROOT=${openarc}/install
fi
if [ ! -f "${OPENARC_INSTALL_ROOT}/make.header" ]; then
    echo "====> Cannot find OpenARC install directory; set environment variable, OPENARC_INSTALL_ROOT properly!"
    exit
fi

openarcinc="${OPENARC_INSTALL_ROOT}/include"
openarclib="${OPENARC_INSTALL_ROOT}/lib"
openarcbin="${OPENARC_INSTALL_ROOT}/bin"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ ! -f "$inputFile" ]; then
	echo "====> [ERROR] cannot find the input file: ${inputFile}; exit!"
	exit	
else
	cp ${inputFile} "vecadd.c"
fi

if [ "$openarcinc" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcinc}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt vecadd.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; vecadd_ACC"
echo ""

