#! /bin/bash
if [ $# -ge 2 ]; then
	inputFile=$1
	verLevel=$2
elif [ $# -eq 1 ]; then
	inputFile=$1
	verLevel=0
else
	inputFile="vecadd.c_v3"
	verLevel=0
fi

openarcrt="../../../../openarcrt"
openarclib="../../../../lib"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ ! -f "$inputFile" ]; then
	echo "====> [ERROR] cannot find the input file: ${inputFile}; exit!"
	exit	
else
	cp ${inputFile} "vecadd.c"
fi

if [ "$openarcrt" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcrt}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt vecadd.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; vecadd_ACC"
echo ""

