#! /bin/bash
if [ $# -ge 2 ]; then
        inputSize=$1
        verLevel=$2
elif [ $# -eq 1 ]; then
        inputSize=$1
        verLevel=0
else
        inputSize=512
        verLevel=0
fi

if [ "${OPENARC_INSTALL_ROOT}" = "" ]; then
    OPENARC_INSTALL_ROOT=${openarc}/install
fi
if [ ! -f "${OPENARC_INSTALL_ROOT}/make.header" ]; then
    echo "====> Cannot find OpenARC install directory; set environment variable, OPENARC_INSTALL_ROOT properly!"
    exit
fi

openarcinc="${OPENARC_INSTALL_ROOT}/include"
openarclib="${OPENARC_INSTALL_ROOT}/lib"
openarcbin="${OPENARC_INSTALL_ROOT}/bin"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$inputSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__inputSize__|${inputSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcinclude" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcinclude__|${openarcinc}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

openarc -verbosity=${verLevel} -gpuConfFile=openarcConf.txt *.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin" 
echo "\$ ./binBuilder_brisbane kernel" 
echo "# For functionality test"
echo "\$ gpu_fpga_matmul_cg_ACC  100 100 1"  
echo "# For performance test"
echo "\$ gpu_fpga_matmul_cg_ACC  10000 10000 1000"
echo ""
