#! /bin/bash
if [ $# -ge 2 ]; then
	inputSize=$1
	compileKernel=$2
elif [ $# -eq 1 ]; then
	inputSize=$1
	compileKernel=1
else
	inputSize=512
	compileKernel=1
fi
verLevel=0

if [ "${OPENARC_INSTALL_ROOT}" = "" ]; then
    OPENARC_INSTALL_ROOT=${openarc}/install
fi
if [ ! -f "${OPENARC_INSTALL_ROOT}/make.header" ]; then
    echo "====> Cannot find OpenARC install directory; set environment variable, OPENARC_INSTALL_ROOT properly!"
    exit
fi

openarcinc="${OPENARC_INSTALL_ROOT}/include"
openarclib="${OPENARC_INSTALL_ROOT}/lib"
openarcbin="${OPENARC_INSTALL_ROOT}/bin"


if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi



if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$inputSize" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__inputSize__|${inputSize}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

if [ "$openarcinc" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcinc}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt acc_helper.c

if [ -f ./cetus_output/acc_helper.cpp ]; then
    cp cetus_output/acc_helper.cpp ./
fi
if [ -f ./cetus_output/openarc_kernel.cu ]; then
    cp ./cetus_output/openarc_kernel.cu ./
    if [ "${compileKernel}" = "1" ] && [ -f "${openarcbin}/binBuilder_cuda" ]; then
        echo ""
        echo "==> Compile kernel file"
        echo ""
        ${openarcbin}/binBuilder_cuda
        cp *.ptx ../ 
    fi  
fi
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; matmul_CUDA"
echo ""

