#! /bin/bash
if [ $# -ge 4 ]; then
	ASYNCMODE=$1
	ITER=$2
	SIZE=$3
	verLevel=$4
elif [ $# -eq 3 ]; then
	ASYNCMODE=$1
	ITER=$2
	SIZE=$3
	verLevel=0
elif [ $# -eq 2 ]; then
	ASYNCMODE=$1
	ITER=$2
	SIZE=1000000
	verLevel=0
elif [ $# -eq 1 ]; then
	ASYNCMODE=$1
	ITER=100
	SIZE=1000000
	verLevel=0
	verLevel=0
else
	ASYNCMODE=0
	ITER=100
	SIZE=1000000
	verLevel=0
fi

if [ "${OPENARC_INSTALL_ROOT}" = "" ]; then
    OPENARC_INSTALL_ROOT=${openarc}/install
fi
if [ ! -f "${OPENARC_INSTALL_ROOT}/make.header" ]; then
    echo "====> Cannot find OpenARC install directory; set environment variable, OPENARC_INSTALL_ROOT properly!"
    exit
fi

openarcinc="${OPENARC_INSTALL_ROOT}/include"
openarclib="${OPENARC_INSTALL_ROOT}/lib"
openarcbin="${OPENARC_INSTALL_ROOT}/bin"

if [ ! -f "openarcConf.txt" ]; then
    cp "openarcConf_NORMAL.txt" "openarcConf.txt"
fi

if [ "$openarcinc" != "" ]; then
    mv "openarcConf.txt" "openarcConf.txt_tmp"
    cat "openarcConf.txt_tmp" | sed "s|__openarcrt__|${openarcinc}|g" > "openarcConf.txt"
    rm "openarcConf.txt_tmp"
fi
mv "openarcConf.txt" "openarcConf.txt_tmp"
cat "openarcConf.txt_tmp" | sed "s|ASYNCMODE|${ASYNCMODE}|g" > "openarcConf.txt"
mv "openarcConf.txt" "openarcConf.txt_tmp"
cat "openarcConf.txt_tmp" | sed "s|NITERS|${ITER}|g" > "openarcConf.txt"
mv "openarcConf.txt" "openarcConf.txt_tmp"
cat "openarcConf.txt_tmp" | sed "s|NSIZE|${SIZE}|g" > "openarcConf.txt"
rm "openarcConf.txt_tmp"

java -classpath $openarclib/cetus.jar:$openarclib/antlr.jar openacc.exec.ACC2GPUDriver -verbosity=${verLevel} -gpuConfFile=openarcConf.txt vecadd_red.c
echo ""
echo "====> To compile the translated output file:"
echo "\$ make"
echo ""
echo "====> To run the compiled binary:"
echo "\$ cd bin; vecadd_red_ACC"
echo ""
